/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const $api: typeof import('./src/utils/api')['$api']
  const EffectScope: typeof import('vue')['EffectScope']
  const TOUR_MESSAGES: typeof import('./src/utils/tourHelpers')['TOUR_MESSAGES']
  const TOUR_SELECTORS: typeof import('./src/utils/tourHelpers')['TOUR_SELECTORS']
  const TourAnalytics: typeof import('./src/utils/tourHelpers')['TourAnalytics']
  const TourDebug: typeof import('./src/utils/tourHelpers')['TourDebug']
  const TourEventManager: typeof import('./src/utils/tourHelpers')['TourEventManager']
  const acceptHMRUpdate: typeof import('pinia')['acceptHMRUpdate']
  const addPieceToFen: typeof import('./src/utils/fenUtils')['addPieceToFen']
  const addTourAttributes: typeof import('./src/utils/tourHelpers')['addTourAttributes']
  const animateInstructionTransition: typeof import('./src/utils/animations')['animateInstructionTransition']
  const api: typeof import('./src/utils/api')['default']
  const computed: typeof import('vue')['computed']
  const createApp: typeof import('vue')['createApp']
  const createPinia: typeof import('pinia')['createPinia']
  const customRef: typeof import('vue')['customRef']
  const dashboardMobileTourSteps: typeof import('./src/utils/tourSteps')['dashboardMobileTourSteps']
  const dashboardTourSteps: typeof import('./src/utils/tourSteps')['dashboardTourSteps']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineComponent: typeof import('vue')['defineComponent']
  const defineStore: typeof import('pinia')['defineStore']
  const effectScope: typeof import('vue')['effectScope']
  const elementExists: typeof import('./src/utils/tourHelpers')['elementExists']
  const exercisesTourSteps: typeof import('./src/utils/tourSteps')['exercisesTourSteps']
  const getActivePinia: typeof import('pinia')['getActivePinia']
  const getAllTours: typeof import('./src/utils/tourConfig')['getAllTours']
  const getAutoStartTours: typeof import('./src/utils/tourConfig')['getAutoStartTours']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const getDashboardTourSteps: typeof import('./src/utils/tourSteps')['getDashboardTourSteps']
  const getTourConfig: typeof import('./src/utils/tourConfig')['getTourConfig']
  const h: typeof import('vue')['h']
  const inject: typeof import('vue')['inject']
  const isProxy: typeof import('vue')['isProxy']
  const isReactive: typeof import('vue')['isReactive']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const mapActions: typeof import('pinia')['mapActions']
  const mapGetters: typeof import('pinia')['mapGetters']
  const mapState: typeof import('pinia')['mapState']
  const mapStores: typeof import('pinia')['mapStores']
  const mapWritableState: typeof import('pinia')['mapWritableState']
  const markRaw: typeof import('vue')['markRaw']
  const navigationTourSteps: typeof import('./src/utils/tourSteps')['navigationTourSteps']
  const nextTick: typeof import('vue')['nextTick']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onMounted: typeof import('vue')['onMounted']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const onWatcherCleanup: typeof import('vue')['onWatcherCleanup']
  const profileTourSteps: typeof import('./src/utils/tourSteps')['profileTourSteps']
  const progressTourSteps: typeof import('./src/utils/tourSteps')['progressTourSteps']
  const provide: typeof import('vue')['provide']
  const puzzlesTourSteps: typeof import('./src/utils/tourSteps')['puzzlesTourSteps']
  const reactive: typeof import('vue')['reactive']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const setActivePinia: typeof import('pinia')['setActivePinia']
  const setMapStoreSuffix: typeof import('pinia')['setMapStoreSuffix']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const specialMovesTourSteps: typeof import('./src/utils/tourSteps')['specialMovesTourSteps']
  const storeToRefs: typeof import('pinia')['storeToRefs']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const toValue: typeof import('vue')['toValue']
  const tourConfigs: typeof import('./src/utils/tourConfig')['tourConfigs']
  const triggerRef: typeof import('vue')['triggerRef']
  const unref: typeof import('vue')['unref']
  const useApi: typeof import('./src/utils/useApi')['useApi']
  const useAttrs: typeof import('vue')['useAttrs']
  const useCookie: typeof import('./src/utils/useCookie')['useCookie']
  const useCssModule: typeof import('vue')['useCssModule']
  const useCssVars: typeof import('vue')['useCssVars']
  const useEmitter: typeof import('./src/utils/useEmitter.js')['default']
  const useId: typeof import('vue')['useId']
  const useModel: typeof import('vue')['useModel']
  const useSlots: typeof import('vue')['useSlots']
  const useTemplateRef: typeof import('vue')['useTemplateRef']
  const validateTourConfig: typeof import('./src/utils/tourHelpers')['validateTourConfig']
  const waitForElement: typeof import('./src/utils/tourHelpers')['waitForElement']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const watchPostEffect: typeof import('vue')['watchPostEffect']
  const watchSyncEffect: typeof import('vue')['watchSyncEffect']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { TourEventManager, TourAnalytics } from './src/utils/tourHelpers'
  import('./src/utils/tourHelpers')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly $api: UnwrapRef<typeof import('./src/utils/api')['$api']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly TOUR_MESSAGES: UnwrapRef<typeof import('./src/utils/tourHelpers')['TOUR_MESSAGES']>
    readonly TOUR_SELECTORS: UnwrapRef<typeof import('./src/utils/tourHelpers')['TOUR_SELECTORS']>
    readonly TourAnalytics: UnwrapRef<typeof import('./src/utils/tourHelpers')['TourAnalytics']>
    readonly TourDebug: UnwrapRef<typeof import('./src/utils/tourHelpers')['TourDebug']>
    readonly TourEventManager: UnwrapRef<typeof import('./src/utils/tourHelpers')['TourEventManager']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly addPieceToFen: UnwrapRef<typeof import('./src/utils/fenUtils')['addPieceToFen']>
    readonly addTourAttributes: UnwrapRef<typeof import('./src/utils/tourHelpers')['addTourAttributes']>
    readonly animateInstructionTransition: UnwrapRef<typeof import('./src/utils/animations')['animateInstructionTransition']>
    readonly api: UnwrapRef<typeof import('./src/utils/api')['default']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly elementExists: UnwrapRef<typeof import('./src/utils/tourHelpers')['elementExists']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useApi: UnwrapRef<typeof import('./src/utils/useApi')['useApi']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useCookie: UnwrapRef<typeof import('./src/utils/useCookie')['useCookie']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly validateTourConfig: UnwrapRef<typeof import('./src/utils/tourHelpers')['validateTourConfig']>
    readonly waitForElement: UnwrapRef<typeof import('./src/utils/tourHelpers')['waitForElement']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}